git:
    depth: 10

language: cpp

matrix:
    include:
        - os:   linux
          dist: trusty
          env:  ATOM_CHANNEL=stable

        - os:   linux
          dist: xenial
          env:  ATOM_CHANNEL=stable

        - os:   linux
          dist: xenial
          env:  ATOM_CHANNEL=beta

        - os:   osx
          env:  ATOM_CHANNEL=stable

        - os:   osx
          env:  ATOM_CHANNEL=beta

notifications:
    email:
        on_success: never
        on_failure: never

script:
    - "curl -s https://raw.githubusercontent.com/Alhadis/Atom-CI/master/dist/main.sh | sh"
