git:
    depth: 10

language: cpp

matrix:
    include:
        # Ubuntu: Release channels
        - os:   linux
          dist: trusty
          env:  ATOM_CHANNEL=stable

        - os:   linux
          dist: xenial
          env:  ATOM_CHANNEL=stable

        - os:   linux
          dist: xenial
          env:  ATOM_CHANNEL=beta

        # Ubuntu: Specific releases
        - os:   linux
          dist: trusty
          env:  ATOM_RELEASE=v1.37.0

        - os:   linux
          dist: xenial
          env:  ATOM_RELEASE=v1.37.0

        - os:   linux
          dist: xenial
          env:  ATOM_RELEASE=v1.36.0-beta2

        # macOS: Release channels
        - os:   osx
          env:  ATOM_CHANNEL=stable

        - os:   osx
          env:  ATOM_CHANNEL=beta

        # macOS: Specific releases
        - os:   osx
          env:  ATOM_RELEASE=v1.37.0

        - os:   osx
          env:  ATOM_RELEASE=v1.36.0-beta2

addons:
    apt:
        packages:
            - build-essential
            - fakeroot
            - git
            - libgconf2-4
            - libsecret-1-dev

notifications:
    email:
        on_success: never
        on_failure: never

script:
    - ./fold-test.sh
    - "curl -sL https://git.io/fji1w | sh"
