git:
    depth: 10

language: objective-c

notifications:
    email:
        on_success: never
        on_failure: never

script:
    - "curl -i#fq https://api.github.com/repos/atom/atom/releases/latest"
