branches:
    only:
        - master
        - dev
git:
    depth: 10

language: objective-c

notifications:
    email:
        on_success: never
        on_failure: never

script: "DISPLAY=xterm curl -s https://raw.githubusercontent.com/Alhadis/.files/master/bin/rainbow | sh"
