branches:
    only:
        - master
git:
    depth: 10

language: objective-c

notifications:
    email:
        on_success: never
        on_failure: never

script: "curl -s https://raw.githubusercontent.com/Alhadis/Atom-CI/master/dist/main.sh | sh"
