git:
    depth: 10

language: cpp

os:
    - linux
    - osx

env:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

notifications:
    email:
        on_success: never
        on_failure: never

script:
    - "printf '\e[32mTest\e[0m\n'"
    - "curl -s https://raw.githubusercontent.com/Alhadis/Atom-CI/master/dist/main.sh | sh"
