git:
    depth: 10

language: objective-c

notifications:
    email:
        on_success: never
        on_failure: never

script:
    - export RAMSAY='salt and peppah'
    - for gordon in $RAMSAY; do printf '<%s>\n' $gordon; done
