git:
    depth: 10

language: objective-c

notifications:
    email:
        on_success: never
        on_failure: never

script:
    - 'printf "\$DISPLAY: %s\n" $DISPLAY'
    - "curl -s https://raw.githubusercontent.com/Alhadis/.files/master/bin/rainbow | DISPLAY=xterm sh | tee"
    - "curl -s https://raw.githubusercontent.com/Alhadis/.files/master/bin/rainbow | DISPLAY=''    sh | tee"
